### ISSUE TITLE
impossibility to calculate percentiles for areas containing nodata values

### ISSUE THREAD

**Issue by fri-end** [perrygeo/python-raster-stats#60]
Hey!
I am experiencing problem when trying to calculate percentiles for areas containing nodata values (in my dataset nodata = 0), while other stats min, max, mean, std works. Here is the error I am getting:
/home/friend/anaconda/lib/python2.7/site-packages/numpy/ma/core.py:3895: UserWarning: Warning: converting a masked element to nan.
  warnings.warn("Warning: converting a masked element to nan.")
Traceback (most recent call last):
  File "/home/friend/PycharmProjects/UbuntuGIS/test_nodata.py", line 277, in <module> all_touched=False, copy_properties=True, band_num=1, nodata_value=0)
  File "/home/friend/anaconda/lib/python2.7/site-packages/rasterstats/main.py", line 316, in zonal_stats  feature_stats[pctile] = np.percentile(masked.compressed(), q)
  File "/home/friend/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3054, in percentile interpolation=interpolation)
  File "/home/friend/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2803, in _ureduce  r = func(a, **kwargs)
  File "/home/friend/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3143, in _percentile x1 = take(ap, indices_below, axis=axis) * weights_below
  File "/home/friend/anaconda/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 121, in take return take(indices, axis, out, mode)
IndexError: cannot do a non-empty take from an empty axes.

1) A link to download the raster and vector dataset necessary to reproduce the error: https://www.dropbox.com/sh/aj54s6anah0ppum/AABs6KyZ3o_eboq_4FRpiaI-a?dl=0

2) Python code to reproduce the error:
stats = zonal_stats('/home/friend/PycharmProjects/OBIA/02_Clumps_38_mult_csv/Plot01_rw_filt2.shp', '/home/friend/PycharmProjects/OBIA/Plot_01_stack_clip2plot_sun.bsq', stats=['count', 'max', 'mean', 'min', 'percentile_25', 'percentile_50', 'percentile_75', 'std'], # 'percentile_25', 'percentile_50', 'percentile_75',  all_touched=False, copy_properties=True, band_num=1, nodata_value=0) 
with open ('/home/friend/PycharmProjects/OBIA/out.csv', 'w') as fh:
             fh.write(stats_to_csv(stats))
del stats

3) Information on my environment: versions of python, gdal and numpy and system memory:
Ubuntu 12.04; Python 2.7.9; GDAL: 1.11.1; Numpy: 1.9.1; Memory: 10 Gb

Please let me know if it's possible to fix.
Cheers,
Yuri

**Comment by perrygeo** [comment]
@fri-end  I'm not sure what's going on here. I was able to reproduce this error thanks to your detailed bug report and I will look into fixing it this weekend. Thanks!
